#!/usr/bin/env python2

from datetime import datetime
import sh
import sys

x = sys.argv

changeset = sh.git("status")

changes_to_be_committed = False
changes_not_staged_for_commit = False
subsyncit_modified = False

for line in changeset.splitlines():

    if line == "Changes to be committed:":
        changes_to_be_committed = True

    if line == "Changes not staged for commit:":
        changes_not_staged_for_commit = True

    if "modified:   subsyncit.py" in line:
        if changes_not_staged_for_commit:
            print "subsyncit.py modified, but you need to git-add it"
            exit(1)
        subsyncit_modified = True

if subsyncit_modified and changes_to_be_committed:

    with open("subsyncit.py", 'r') as f:
        get_all = f.readlines()

    newlines = []
    for i, line in enumerate(get_all):
        if i == 4:
            newlines.append("# Version: " + str(datetime.utcnow()) + " (UTC)\n")
        else:
            newlines.append(line)

    with open("subsyncit.py", 'w') as f:
        f.writelines(newlines)


