#!/usr/bin/env python3

import glob
import os
import shutil

import sh

def change_to_parent_resources_and_remove_timesstamps(dir, srcfile):
    sh.sed("-i", '', 's/src="k/src="..\/k/', dir + os.sep + srcfile)
    sh.sed("-i", '', 's/src="j/src="..\/j/', dir + os.sep + srcfile)
    sh.sed("-i", '', 's/src="c/src="..\/c/', dir + os.sep + srcfile)
    sh.sed("-i", '', 's/style.css/..\/style.css/', dir + os.sep + srcfile)
    sh.sed("-i", '', '/created at 20/d', dir + os.sep + srcfile)


for f in glob.glob("docs/coverage_reports" + os.sep + "test*"):
    shutil.rmtree(f)

all_coverages_args = ["combine"]
index_page = '<html><body>\n'

for test in glob.glob("integrationTests/*"):
    testname = ""
    with open(test + os.sep + ".testname", 'r') as f:
        testname = "".join(f.readlines())
    one = test + os.sep + "one" + os.sep + ".coverage"
    two = test + os.sep + "two" + os.sep + ".coverage"
    if os.path.exists(one) and os.path.exists(two):
        sh.cp(one, one + ".copy")
        sh.cp(two, two + ".copy")
        sh.coverage("combine", one, two)
        sh.cp(two + ".copy", two)
        sh.cp(one + ".copy", one)
        all_coverages_args.append(one)
        all_coverages_args.append(two)
    elif os.path.exists(one):
        sh.cp(one, one + ".copy")
        sh.coverage("combine", one)
        sh.cp(one + ".copy", one)
        all_coverages_args.append(one)
    else:
        print ("oops")
        continue
    sh.coverage("html", "-d", "docs/coverage_reports" + os.sep + testname, "--include", "subsyncit.py")
    for f in glob.glob("docs/coverage_reports" + os.sep + testname + os.sep + "*.css"):
        os.remove(f)
    for f in glob.glob("docs/coverage_reports" + os.sep + testname + os.sep + "*.js"):
        os.remove(f)
    for f in glob.glob("docs/coverage_reports" + os.sep + testname + os.sep + "*.png"):
        os.remove(f)
    sh.git("add", "docs/coverage_reports" + os.sep + testname)
    change_to_parent_resources_and_remove_timesstamps("docs/coverage_reports" + os.sep + testname, "subsyncit_py.html")
    change_to_parent_resources_and_remove_timesstamps("docs/coverage_reports" + os.sep + testname, "index.html")
    index_page += '<a href="' + testname + '">' + testname + '</a><br>\n'
sh.coverage(all_coverages_args)
sh.coverage("html", "-d", "docs/coverage_reports" + os.sep + "all", "--include", "subsyncit.py")
change_to_parent_resources_and_remove_timesstamps("docs/coverage_reports" + os.sep + "all", "subsyncit_py.html")
change_to_parent_resources_and_remove_timesstamps("docs/coverage_reports" + os.sep + "all", "index.html")
index_page += '</body></html><br>\n<a href="all">all</a>'
with open("docs/coverage_reports" + os.sep + "index.html", "w") as text_file:
    text_file.write(index_page)
sh.git("add", "docs/coverage_reports")