#!/usr/bin/env python3

import glob

import os

import sh

for test in glob.glob("integrationTests/*"):
    index_page = '<html><body>\n'
    testname = ""
    with open(test + os.sep + ".testname", 'r') as f:
        testname = "".join(f.readlines())
    print(testname)
    one = test + os.sep + "one" + os.sep + ".coverage"
    two = test + os.sep + "two" + os.sep + ".coverage"
    if os.path.exists(one) and os.path.exists(two):
        sh.coverage("combine", one, two)
    elif os.path.exists(one):
        sh.coverage("combine", one)
    else:
        continue
    sh.coverage("html", "-d", "docs/coverage_reports" + os.sep + testname, "--include", "subsyncit.py")
    sh.git("add", "docs/coverage_reports" + os.sep + testname)
    sh.sed("-i", "''", '\'s/src="/src="..\//\'', "docs/coverage_reports" + os.sep + testname + os.sep, "subsyncit.py.html")
    sh.sed("-i", "''",  "'s/style.css/..\/style.css/'", "docs/coverage_reports" + os.sep + testname + os.sep, "subsyncit.py.html")
    index_page + '<a href="' + testname + '">' + testname + '</a><br>\n'
index_page += '</body></html>'
with open("docs/coverage_reports" + os.sep + "index.html", "w") as text_file:
    text_file.write(index_page)